p8105_hw3_zn2220
================
Ziang Niu
2025-10-02

``` r
library(tidyverse)
library(p8105.datasets)
library(lubridate)
library(janitor)
library(knitr)
library(patchwork)
library(RNHANES)
```

# Problem 1

## 1.0

### To that end, write a short description of the dataset, noting the size and structure of the data, describing some key variables, and giving illstrative examples of observations.

Introducing data.

``` r
data("instacart")
instacart <- janitor::clean_names(instacart)
```

Monitor the data. It has 1384617 rows and 15 cols. Let’s glimpse at it
and make a slice. Some key variables and example are shown in the kable.

``` r
glimpse(instacart)
```

    ## Rows: 1,384,617
    ## Columns: 15
    ## $ order_id               <int> 1, 1, 1, 1, 1, 1, 1, 1, 36, 36, 36, 36, 36, 36,…
    ## $ product_id             <int> 49302, 11109, 10246, 49683, 43633, 13176, 47209…
    ## $ add_to_cart_order      <int> 1, 2, 3, 4, 5, 6, 7, 8, 1, 2, 3, 4, 5, 6, 7, 8,…
    ## $ reordered              <int> 1, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1, 1, 1, 1, 1,…
    ## $ user_id                <int> 112108, 112108, 112108, 112108, 112108, 112108,…
    ## $ eval_set               <chr> "train", "train", "train", "train", "train", "t…
    ## $ order_number           <int> 4, 4, 4, 4, 4, 4, 4, 4, 23, 23, 23, 23, 23, 23,…
    ## $ order_dow              <int> 4, 4, 4, 4, 4, 4, 4, 4, 6, 6, 6, 6, 6, 6, 6, 6,…
    ## $ order_hour_of_day      <int> 10, 10, 10, 10, 10, 10, 10, 10, 18, 18, 18, 18,…
    ## $ days_since_prior_order <int> 9, 9, 9, 9, 9, 9, 9, 9, 30, 30, 30, 30, 30, 30,…
    ## $ product_name           <chr> "Bulgarian Yogurt", "Organic 4% Milk Fat Whole …
    ## $ aisle_id               <int> 120, 108, 83, 83, 95, 24, 24, 21, 2, 115, 53, 1…
    ## $ department_id          <int> 16, 16, 4, 4, 15, 4, 4, 16, 16, 7, 16, 4, 16, 2…
    ## $ aisle                  <chr> "yogurt", "other creams cheeses", "fresh vegeta…
    ## $ department             <chr> "dairy eggs", "dairy eggs", "produce", "produce…

``` r
set.seed(235)
instacart_examples <- instacart %>% 
  slice_sample(n = 5) %>% 
  select(order_id, product_name, aisle, department, order_dow, order_hour_of_day)

knitr::kable(instacart_examples, caption = "Illustrative sample of Instacart orders")
```

| order_id | product_name | aisle | department | order_dow | order_hour_of_day |
|---:|:---|:---|:---|---:|---:|
| 3258129 | Organic Extra Firm Tofu | tofu meat alternatives | deli | 0 | 15 |
| 2741482 | Organic Powdered Sugar | baking ingredients | pantry | 3 | 11 |
| 651769 | Special K Protein Milk Chocolate Protein Shakes | protein meal replacements | personal care | 3 | 17 |
| 859477 | Variety Pack | food storage | household | 2 | 9 |
| 1788253 | Organic Grape Tomatoes | packaged vegetables fruits | produce | 0 | 16 |

Illustrative sample of Instacart orders

Important variables include order_id (unique identifier for each order),
product_name (the specific item purchased), aisle (store aisle),
department (broader store department), order_dow (day of week; 0 =
Sunday, 6 = Saturday), and order_hour_of_day (hour of day). Illustrative
examples highlight how these variables describe customer behavior:

In order 3258129, the customer purchased Organic Extra Firm Tofu from
the tofu meat alternatives aisle in the deli department, placed on
Sunday (day 0) at 3 PM.

In order 2741482, Organic Powdered Sugar was bought from the baking
ingredients aisle in the pantry department, placed on Wednesday (day 3)
at 11 AM.

In order 651769, Special K Protein Milk Chocolate Protein Shakes came
from the protein meal replacements aisle in the personal care
department, placed on Wednesday (day 3) at 5 PM.

In order 859477, Variety Pack was purchased from the food storage aisle
in the household department, placed on Tuesday (day 2) at 9 AM.

In order 1788253, Organic Grape Tomatoes came from the packaged
vegetables fruits aisle in the produce department, placed on Sunday (day
0) at 4 PM.

## 1.1

### How many aisles are there, and which aisles are the most items ordered from?

Count the total number of aisles and identify the one with the most
items ordered.

``` r
aisle_counts <- instacart %>%
  count(aisle, name = "n_items") %>%
  arrange(desc(n_items))

n_aisles <- nrow(aisle_counts)

top_aisle <- aisle_counts %>%
  slice(1)
```

It has 134 aisles, the tibble below shows the the one with the most
items ordered.

``` r
top_aisle
```

    ## # A tibble: 1 × 2
    ##   aisle            n_items
    ##   <chr>              <int>
    ## 1 fresh vegetables  150609

## 1.2

### Make a plot that shows the number of items ordered in each aisle, limiting this to aisles with more than 10000 items ordered. Arrange aisles sensibly, and organize your plot so others can read it.

``` r
aisle_counts %>%
  filter(n_items > 10000) %>%
  ggplot(aes(
    x = fct_reorder(aisle, n_items), 
    y = n_items
  )) +
  geom_col(fill = "navy", alpha = 0.9) +
  coord_flip() +
  labs(
    title = "Top Instacart Aisles by Number of Items Ordered (> 10,000)",
    x = "Aisle Name (Sorted by Order Count)",
    y = "Total Number of Items Ordered",
    caption = "Source: Instacart Data"
  ) +
  scale_y_continuous(labels = scales::comma) +
  theme_minimal(base_size = 10) +
  theme(
    plot.title.position = "plot",
    panel.grid.minor = element_blank(),
    plot.caption = element_text(color = "grey50")
  )
```

![](p8105_hw3_zn2220_files/figure-gfm/unnamed-chunk-6-1.png)<!-- -->

## 1.3

### Make a table showing the three most popular items in each of the aisles “baking ingredients”, “dog food care”, and “packaged vegetables fruits”. Include the number of times each item is ordered in your table.

``` r
target_aisles <- c("baking ingredients", "dog food care", "packaged vegetables fruits")

popular_items <- instacart %>%
  filter(aisle %in% target_aisles) %>%
  count(aisle, product_name, name = "order_count") %>%
  group_by(aisle) %>%
  slice_max(order_count, n = 3, with_ties = FALSE) %>%
  ungroup() %>%
  arrange(aisle, desc(order_count))

kable(popular_items, caption = "Top 3 Most Popular Items in Selected Aisles")
```

| aisle | product_name | order_count |
|:---|:---|---:|
| baking ingredients | Light Brown Sugar | 499 |
| baking ingredients | Pure Baking Soda | 387 |
| baking ingredients | Cane Sugar | 336 |
| dog food care | Snack Sticks Chicken & Rice Recipe Dog Treats | 30 |
| dog food care | Organix Chicken & Brown Rice Recipe | 28 |
| dog food care | Small Dog Biscuits | 26 |
| packaged vegetables fruits | Organic Baby Spinach | 9784 |
| packaged vegetables fruits | Organic Raspberries | 5546 |
| packaged vegetables fruits | Organic Blueberries | 4966 |

Top 3 Most Popular Items in Selected Aisles

## 1.4

### Make a table showing the mean hour of the day at which Pink Lady Apples and Coffee Ice Cream are ordered on each day of the week; format this table for human readers (i.e. produce a 2 x 7 table).

``` r
target_products <- c("Pink Lady Apples", "Coffee Ice Cream")

mean_hour_table <- instacart %>%
  filter(product_name %in% target_products) %>%
  group_by(product_name, order_dow) %>%
  summarize(mean_order_hour = mean(order_hour_of_day, na.rm = TRUE), .groups = 'drop') %>%
  pivot_wider(
    names_from = order_dow,
    values_from = mean_order_hour
  ) %>%
  mutate(across(where(is.numeric), ~round(., 2)))

day_names <- c("Sun", "Mon", "Tue", "Wed", "Thu", "Fri", "Sat")

colnames(mean_hour_table)[2:8] <- day_names

kable(mean_hour_table, caption = "Mean Order Hour of Day by Product and Day of Week")
```

| product_name     |   Sun |   Mon |   Tue |   Wed |   Thu |   Fri |   Sat |
|:-----------------|------:|------:|------:|------:|------:|------:|------:|
| Coffee Ice Cream | 13.77 | 14.32 | 15.38 | 15.32 | 15.22 | 12.26 | 13.83 |
| Pink Lady Apples | 13.44 | 11.36 | 11.70 | 14.25 | 11.55 | 12.78 | 11.94 |

Mean Order Hour of Day by Product and Day of Week
